services:
  api:
    build: .
    ports:
      - ${PORT}:8080
    environment:
      PORT: ${PORT}
      MONGO_URI: mongodb://${DB_USERNAME}:${DB_PASSWORD}@mongo:27017/
      DB_NAME: ${DB_NAME}
    develop:
      watch:
        - path: .
          action: rebuild

    depends_on:
      - mongo

  mongo:
    image: mongo:8
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    volumes:
      - mongo-data:/data/db

  mongo-seed:
    build: ./seed
    environment:
      MONGO_USERNAME: ${DB_USERNAME}
      MONGO_PASSWORD: ${DB_PASSWORD}
      MONGO_NAME: ${DB_NAME}
    depends_on:
      - mongo


volumes:
  mongo-data: